//
//  LoginPresenter.swift
//  PersonalFinances
//
//  Created by Ruth Ellen da Silva on 15/12/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic {
    func presentResponse(response: Login.Logar.Response)
}

class LoginPresenter: LoginPresentationLogic {
    
    weak var viewController: LoginDisplayLogic?
    

    // MARK: Parse and calc respnse from LoginInteractor and send simple view model to LoginViewController to be displayed

    func presentResponse(response: Login.Logar.Response) {
        var viewModel: Login.Logar.ViewModel
        
        switch response.value {
        case 0:
            viewModel = Login.Logar.ViewModel(mensagem: "Sucesso")
        case 1:
            viewModel = Login.Logar.ViewModel(mensagem: "Usuário não pode estar vazio")
        case 2:
            viewModel = Login.Logar.ViewModel(mensagem: "Senha não pode estar vazia")
        default:
            viewModel = Login.Logar.ViewModel(mensagem: "Usuário ou senha incorretos")
        }

        viewController?.displayResult(viewModel: viewModel)
    }

}
