//
//  LoginModels.swift
//  PersonalFinances
//
//  Created by Ruth Ellen da Silva on 15/12/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login
{
    // MARK: Use cases

    enum Logar
    {
        struct Request
        {
            let user: String
            let pass: String
        }

        struct Response
        {
            let value: Int
            //0 -> success
            //1 -> user vazio
            //2 -> pass vazio
            //3 -> nao existe usuario
        }

        struct ViewModel
        {
            let mensagem: String
        }
    }
    
//    enum SomethingElse
//    {
//        struct Request
//        {
//
//        }
//
//        struct Response
//        {
//
//        }
//
//        struct ViewModel
//        {
//
//        }
//    }
}
