//
//  LoginRouter.swift
//  PersonalFinances
//
//  Created by Ruth Ellen da Silva on 15/12/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic {
    func routeToHome()
}

class LoginRouter: NSObject, LoginRoutingLogic {
    
    weak var viewController: LoginViewController?

// MARK: Routing (navigating to other screens)

    func routeToHome() {
        let sb = UIStoryboard(name: "Main", bundle: nil)
        let ftb = sb.instantiateViewController(withIdentifier: "main") as! UINavigationController
        ftb.modalPresentationStyle = .fullScreen
        viewController?.show(ftb, sender: nil)
    }
}
