//
//  LoginInteractor.swift
//  PersonalFinances
//
//  Created by Ruth Ellen da Silva on 15/12/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogic {
    func handleFetchLogin(request: Login.Logar.Request)
}

class LoginInteractor: LoginBusinessLogic {
    
    var presenter: LoginPresentationLogic?
    var worker: LoginWorkerLogic?

    
    // MARK: Handle Fetch Login (and send response to LoginPresenter)
    
    func handleFetchLogin(request: Login.Logar.Request) {
                
        if request.user.isEmpty  {
            presenter?.presentResponse(response: .init(value: 1))
            return
        }
        
        if request.pass.isEmpty {
            presenter?.presentResponse(response: .init(value: 2))
            return
        }
        
        worker = LoginWorker()
        worker?.requestLogin(request: request, completion: { (boolean) in
            if boolean {
                self.presenter?.presentResponse(response: .init(value: 0))
                return
            } else {
                self.presenter?.presentResponse(response: .init(value: 3))
                return

            }
        })
        
    }
}
