//
//  FinancasModels.swift
//  PersonalFinances
//
//  Created by Ruth Ellen da Silva on 17/12/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Financas
{
    // MARK: Use cases

    enum FinancaResponse
    {
        struct Financa: Codable
        {
            let idUser: Int
            let totalExpense: Double
            let totalIncome: Double
            let financialIncomeResponseList: [Financas.FinancaResponse.Get]
            let financialExpensesResponseList: [Financas.FinancaResponse.Get]
        }

        struct ViewModel
        {
            let totalExpense: String
            let totalIncome: String
            let total: String
            let financialIncomeResponseList: [Financas.FinancaResponse.Get]
            let financialExpensesResponseList: [Financas.FinancaResponse.Get]
        }
        
        struct Get: Codable
        {
            let id: Int
            let idUser: Int
            let tipo: String
            let dataMovimentacao: String
            let descricao: String
            let categoria: String
            let valor: Double
            let createdAt: String
            let modifiedAt: String
        }
    }
}
