//
//  FinancasPresenter.swift
//  PersonalFinances
//
//  Created by Ruth Ellen da Silva on 17/12/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FinancasPresentationLogic {
    func presentFinances(response: Financas.FinancaResponse.Financa)
}

class FinancasPresenter: FinancasPresentationLogic {
    
    weak var viewController: FinancasDisplayLogic?

    // MARK: Parse and calc respnse from FinancasInteractor and send simple view model to FinancasViewController to be displayed

    func presentFinances(response: Financas.FinancaResponse.Financa) {
        let viewModel = Financas.FinancaResponse.ViewModel(
            totalExpense: "R$ \(String(format: "%.02f", response.totalExpense))" ,
            totalIncome: "R$ \(String(format: "%.02f", response.totalIncome))",
            total: "R$ \(String(format: "%.02f", response.totalIncome - response.totalExpense))",
            financialIncomeResponseList: response.financialIncomeResponseList,
            financialExpensesResponseList: response.financialExpensesResponseList)
        viewController?.displayFinances(viewModel: viewModel)
    }
    

}
