//
//  FinancasWorker.swift
//  PersonalFinances
//
//  Created by Ruth Ellen da Silva on 17/12/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FinancasWorkerLogic {
    func requestFinancas(completion: @escaping (Financas.FinancaResponse.Financa?) -> Void)
}

class FinancasWorker: FinancasWorkerLogic {
    
    func requestFinancas(completion: @escaping (Financas.FinancaResponse.Financa?) -> Void) {
        
        let basePath = ServiceRepository.shared.basePath
        let session = ServiceRepository.shared.session
        
        guard let url = URL(string: basePath + "/financial") else {
            completion(nil)
            return
        }
        
        let dataTask = session.dataTask(with: url) { (data, response, error) in
            if error == nil {
                guard let response = response as? HTTPURLResponse else {
                    completion(nil)
                    return
                }
                if response.statusCode == 200 {
                    guard let data = data else { return }
                    if data.isEmpty {
                        completion(nil)
                        return
                    }
                    do {
                        let finances = try JSONDecoder().decode(Financas.FinancaResponse.Financa.self, from: data)
                        completion(finances)
                    } catch _ as NSError {
                        completion(nil)
                    }
                } else {
                    completion(nil)
                }
            } else {
                completion(nil)
            }
        }
        
        dataTask.resume()
    }
    

}
