//
//  FinancasRouter.swift
//  PersonalFinances
//
//  Created by Ruth Ellen da Silva on 17/12/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol FinancasRoutingLogic {
    func routeToNovaFinanca()
}

class FinancasRouter: NSObject, FinancasRoutingLogic {
    
    weak var viewController: FinancasViewController?
    
    func routeToNovaFinanca() {
        viewController?.performSegue(withIdentifier: "novaFinanca", sender: nil)
    }
}
