//
//  FinancasInteractor.swift
//  PersonalFinances
//
//  Created by Ruth Ellen da Silva on 17/12/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FinancasBusinessLogic {
    func handleFetchFinances()
}

class FinancasInteractor: FinancasBusinessLogic {
    
    var presenter: FinancasPresentationLogic?
    var worker: FinancasWorkerLogic?

    // MARK: Do something (and send response to FinancasPresenter)
    
    func handleFetchFinances() {
        worker = FinancasWorker()
        worker?.requestFinancas(completion: { (finances) in
            guard let responseFinances = finances else {
                return
            }
            
            self.presenter?.presentFinances(response: responseFinances)
        })
    }
}
