//
//  NovaFinancaPresenter.swift
//  PersonalFinances
//
//  Created by Ruth Ellen da Silva on 27/12/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NovaFinancaPresentationLogic {
    func presentResult(response: NovaFinanca.Financa.Response)
    
    func presentDataLimit(date: Date)
}

class NovaFinancaPresenter: NovaFinancaPresentationLogic {
    weak var viewController: NovaFinancaDisplayLogic?

    // MARK: Parse and calc respnse from NovaFinancaInteractor and send simple view model to NovaFinancaViewController to be displayed
    
    func presentResult(response: NovaFinanca.Financa.Response) {
        if response.response {
            viewController?.redirect()
        } else {
            viewController?.erro()
        }
    }
    
    func presentDataLimit(date: Date) {
        viewController?.displayDateLimit(date: date)
    }
}
