//
//  NovaFinancaWorker.swift
//  PersonalFinances
//
//  Created by Ruth Ellen da Silva on 27/12/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NovaFinancaWorkerLogic {
    func postFinance(financa: NovaFinanca.Financa.Request, completion: @escaping (NovaFinanca.Financa.Response) -> Void)
}

class NovaFinancaWorker: NovaFinancaWorkerLogic {
    
    func postFinance(financa: NovaFinanca.Financa.Request, completion: @escaping (NovaFinanca.Financa.Response) -> Void) {
        
        let basePath = ServiceRepository.shared.basePath
        let session = ServiceRepository.shared.session
        
        guard let url = URL(string: basePath + "/financial") else {
            completion(.init(response: false))
            return
        }
        
        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        guard let json = try? JSONEncoder().encode(financa) else {
            completion(.init(response: false))
            return
        }
        
        request.httpBody = json
        
        let dataTask = session.dataTask(with: request) { (data, response, error) in
            if error == nil {
                guard let response = response as? HTTPURLResponse, response.statusCode == 201, let _ = data else {
                    completion(.init(response: false))
                    return
                }
                completion(.init(response: true))
            } else {
                completion(.init(response: false))
            }
        }
        dataTask.resume()
    }
    

}
