//
//  NovaFinancaRouter.swift
//  PersonalFinances
//
//  Created by Ruth Ellen da Silva on 27/12/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol NovaFinancaRoutingLogic {
    func routeBackToFinances()
}

class NovaFinancaRouter: NSObject, NovaFinancaRoutingLogic {
    
    weak var viewController: NovaFinancaViewController?

// MARK: Routing (navigating to other screens)
    
    func routeBackToFinances() {
        viewController?.navigationController?.popViewController(animated: true)
    }
}
